"""
Anima LoRA Training Config Template for Kohya sd-scripts

Generates TOML configuration files for anima_train_network.py

Anima is a DiT (Diffusion Transformer) model by Circlestone Labs using
Rectified Flow training, a Qwen3-0.6B text encoder, an LLM Adapter bridge,
and the Qwen-Image VAE (16ch, 8x downscale).
"""


def generate_anima_training_config(
    name: str,
    image_folder: str,
    output_folder: str,
    ckpt_path: str,
    qwen3_path: str,
    vae_path: str,
    steps: int = 500,
    learning_rate: float = 0.0001,
    lora_rank: int = 16,
    lora_alpha: int = 1,
    resolution: int = 1024,
    batch_size: int = 1,
    optimizer: str = "AdamW8bit",
    mixed_precision: str = "bf16",
    gradient_checkpointing: bool = True,
    cache_latents: bool = True,
    cache_text_encoder_outputs: bool = True,
    blocks_to_swap: int = 0,
    timestep_sampling: str = "sigmoid",
    discrete_flow_shift: float = 1.0,
    train_llm_adapter: bool = False,
    llm_adapter_lr: float = 0.00005,
    vae_chunk_size: int = 0,
    vae_disable_cache: bool = False,
    save_every_n_epochs: int = 0,
    save_every_n_steps: int = 0,
    save_last_n_epochs: int = 0,
) -> str:
    """
    Generate a TOML config file for Anima LoRA training with sd-scripts.

    Returns the config as a TOML string.
    """

    # Escape backslashes for TOML on Windows
    ckpt_path_escaped = ckpt_path.replace("\\", "/")
    qwen3_path_escaped = qwen3_path.replace("\\", "/")
    vae_path_escaped = vae_path.replace("\\", "/")
    image_folder_escaped = image_folder.replace("\\", "/")
    output_folder_escaped = output_folder.replace("\\", "/")

    config = f'''# Anima LoRA Training Config
# Generated by ComfyUI Anima LoRA Trainer

[general]
enable_bucket = true
bucket_no_upscale = true
max_bucket_reso = 2048

[model]
pretrained_model_name_or_path = "{ckpt_path_escaped}"
qwen3 = "{qwen3_path_escaped}"
vae = "{vae_path_escaped}"

[dataset]
train_data_dir = "{image_folder_escaped}"
resolution = "{resolution},{resolution}"
caption_extension = ".txt"

[network]
network_module = "networks.lora_anima"
network_dim = {lora_rank}
network_alpha = {lora_alpha}
network_train_unet_only = true

[optimizer]
optimizer_type = "{optimizer}"
learning_rate = {learning_rate:g}
lr_scheduler = "constant"

[anima]
timestep_sampling = "{timestep_sampling}"
discrete_flow_shift = {discrete_flow_shift:g}

[training]
output_dir = "{output_folder_escaped}"
output_name = "{name}"
save_model_as = "safetensors"
save_precision = "bf16"
max_train_steps = {steps}
train_batch_size = {batch_size}
mixed_precision = "{mixed_precision}"
gradient_checkpointing = {str(gradient_checkpointing).lower()}
cache_latents = {str(cache_latents).lower()}
cache_text_encoder_outputs = {str(cache_text_encoder_outputs).lower()}
sdpa = true
max_data_loader_n_workers = 0
seed = 42
'''

    # Optional VRAM helpers
    if blocks_to_swap and blocks_to_swap > 0:
        config += f"blocks_to_swap = {blocks_to_swap}\n"
    if vae_chunk_size and vae_chunk_size > 0:
        config += f"vae_chunk_size = {vae_chunk_size}\n"
    if vae_disable_cache:
        config += "vae_disable_cache = true\n"

    # Intermediate checkpoint saving. Epoch files are saved into output_dir
    # as {output_name}-{epoch:06d}.safetensors (steps: -step{:08d}).
    if save_every_n_epochs and save_every_n_epochs > 0:
        config += f"save_every_n_epochs = {save_every_n_epochs}\n"
        if save_last_n_epochs and save_last_n_epochs > 0:
            config += f"save_last_n_epochs = {save_last_n_epochs}\n"
    if save_every_n_steps and save_every_n_steps > 0:
        config += f"save_every_n_steps = {save_every_n_steps}\n"

    # LLM Adapter LoRA training (off by default). Lowering the adapter LR
    # improves stability per the sd-scripts Anima docs.
    if train_llm_adapter:
        config += (
            "\n[network_extra]\n"
            f'network_args = ["train_llm_adapter=True", "network_reg_lrs=.*llm_adapter.*={llm_adapter_lr:g}"]\n'
        )

    return config


def save_config(config_content: str, config_path: str):
    """Save config content to a TOML file."""
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(config_content)


# VRAM mode presets for Anima (rank is user-controlled, not preset)
# Anima-Preview is a 28-block DiT; blocks_to_swap max is 26 for that size.
ANIMA_VRAM_PRESETS = {
    "Min (512px)": {
        "optimizer": "AdamW8bit",
        "mixed_precision": "bf16",
        "batch_size": 1,
        "gradient_checkpointing": True,
        "cache_latents": True,
        "cache_text_encoder_outputs": True,
        "resolution": 512,
        "blocks_to_swap": 16,
        "vae_chunk_size": 64,
        "vae_disable_cache": True,
    },
    "Low (768px)": {
        "optimizer": "AdamW8bit",
        "mixed_precision": "bf16",
        "batch_size": 1,
        "gradient_checkpointing": True,
        "cache_latents": True,
        "cache_text_encoder_outputs": True,
        "resolution": 768,
        "blocks_to_swap": 8,
        "vae_chunk_size": 64,
        "vae_disable_cache": True,
    },
    "Max (1024px)": {
        "optimizer": "AdamW8bit",
        "mixed_precision": "bf16",
        "batch_size": 1,
        "gradient_checkpointing": True,
        "cache_latents": True,
        "cache_text_encoder_outputs": True,
        "resolution": 1024,
        "blocks_to_swap": 0,
        "vae_chunk_size": 0,
        "vae_disable_cache": False,
    },
}
